# Generated by Django 4.2 on 2023-05-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalEncontrado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='animais')),
                ('data_encontrado', models.DateField()),
                ('local_encontrado', models.CharField(max_length=100)),
                ('nome_encontrou', models.CharField(default='Desconhecido', max_length=100)),
                ('tel_encontrou', models.CharField(default='00', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalPerdido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='animais')),
                ('data_perdido', models.DateField()),
                ('local_perdido', models.CharField(max_length=100)),
                ('nome_perdeu', models.CharField(default='Desconhecido', max_length=100)),
                ('tel_perdeu', models.CharField(default='00', max_length=11)),
            ],
        ),
    ]
