# Generated by Django 4.2 on 2023-05-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cade_meu_pet', '0002_alter_animalencontrado_id_alter_animalperdido_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalencontrado',
            name='foto',
            field=models.ImageField(upload_to='foto_perdidos/'),
        ),
        migrations.AlterField(
            model_name='animalperdido',
            name='foto',
            field=models.ImageField(upload_to='foto_encontrados/'),
        ),
    ]
