# Generated by Django 4.2 on 2023-05-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cade_meu_pet', '0003_alter_animalencontrado_foto_alter_animalperdido_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalencontrado',
            name='data_encontrado',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='animalperdido',
            name='data_perdido',
            field=models.CharField(max_length=10),
        ),
    ]
