# Generated by Django 4.2 on 2023-05-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cade_meu_pet', '0004_alter_animalencontrado_data_encontrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalencontrado',
            name='data_encontrado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animalencontrado',
            name='tel_encontrou',
            field=models.CharField(default='00', max_length=100),
        ),
        migrations.AlterField(
            model_name='animalperdido',
            name='data_perdido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animalperdido',
            name='tel_perdeu',
            field=models.CharField(default='00', max_length=100),
        ),
    ]
