# Generated by Django 4.2 on 2023-05-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cade_meu_pet', '0005_alter_animalencontrado_data_encontrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalencontrado',
            name='data_encontrado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='animalperdido',
            name='data_perdido',
            field=models.DateField(),
        ),
    ]
